version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sourceFromCodeDeploy
hooks:
  BeforeInstall:
    - location: devops/scripts/remove_root_dir
      timeout: 900
      runas: ubuntu
  AfterInstall:
    - location: ./devops/hooks/after-install.sh
      runas: ubuntu
  ApplicationStart:
    - location: devops/scripts/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: devops/scripts/stop_server
      timeout: 300
      runas: ubuntu